import numpy as np
from uproot_custom.cpp import IReader

class JMSmartRefReader(IReader):
    def __init__(self, name: str): ...
    def data(self) -> tuple[np.ndarray, np.ndarray]: ...

class AnyNotTObjClassReader(IReader):
    def __init__(self, name: str, element_readers: list[IReader]): ...
    def data(self) -> list[np.ndarray]: ...

class AnyJMClassReader(IReader):
    def __init__(self, name: str, element_reader: IReader): ...
    def data(self) -> np.ndarray: ...
