changelog:
  categories:
    - title: New Features
      labels:
        - feature
    - title: Bug Fixes and Performance Improvements
      labels:
        - bug
        - fix
        - performance
    - title: Refactorings
      labels:
        - refactor
    - title: Other Changes
      labels:
        - '*'
